services:
  # Meteor-Enterprise:
  #   container_name: meteor-enterprise
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "MeteorFlow2024"
  #     ACCEPT_EULA: "Y"
      
  meteor-gis:
    container_name: meteor-gis
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "meteor"
      POSTGRES_PASSWORD: "MeteorFlow2024"
      POSTGRES_DB: "core"
  
  meteor-auth:
    container_name: meteor-auth
    image: postgres:latest
    ports:
      - "5632:5432"
    environment:
      POSTGRES_USER: "meteor"
      POSTGRES_PASSWORD: "MeteorFlow2024"
      POSTGRES_DB: "auth"
  
  meteor-form:
    container_name: meteor-form
    image: postgres:latest
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: "meteor"
      POSTGRES_PASSWORD: "MeteorFlow2024"
      POSTGRES_DB: "form_builder"

  cache:
    container_name: cache-api
    image: redis:latest
    ports:
      - "6380:6380"
    command: ["redis-server", "--requirepass", "MeteorFlow2024"]

  