name: meteorflow

services:
  # web:
  #   build:
  #     context: ../src/MeteorFlow.Web
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - ${WEB_PORT}:3000
  #   deploy:
  #     resources:
  #       reservations:
  #         cpus: "0.2"
  #         memory: 50M
  #       limits:
  #         cpus: "0.5"
  #         memory: 200M
  #   networks:
  #     - meteorflow-network

  backend:
    # Always use the latest image
    image: ghcr.io/meteorflow/meteor-flow-backend:latest
    environment:
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - ConnectionStrings__PGConnection=${ConnectionStrings__PGConnection}
    ports:
      - ${API_PORT}:8080
    deploy:
      resources:
        reservations:
          cpus: "0.2"
          memory: 50M
        limits:
          cpus: "2"
          memory: 200M
    networks:
      - meteorflow-network

networks:
  meteorflow-network:
    name: meteorflow-network
    external: true
