name: meteorflow

services:
  postgres:
    image: postgres:15.6-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6380"
    networks:
      - meteorflow-network

volumes:
  mssql-volume:

networks:
  meteorflow-network:
    name: meteorflow-network
