name: Deploy on Raspberry Pi

on:
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/MeteorFlow/meteor-flow-backend
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.meta.outputs.tags }}

  redeploy:
    name: Redeploy
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: Pull commits and trigger Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RASPI_HOST }}
          username: ${{ secrets.RASPI_USERNAME }}
          key: ${{ secrets.RASPI_SSH_KEY }}
          script: |
            cd MeteorFlow
            git fetch --prune origin
            git pull
            docker compose -f docker/docker-compose.prod.yaml up -d
